### PR TITLE
[Feature Update]: File storage

### PR DESCRIPTION
**Pull request by Only1allan**

### CODE REVIEW

**Review by kariukikinyanjui — APPROVED** [review]
The key construction method in your implementation involves an additional step of converting the object to a dictionary before extracting the necessary information. This may introduce a slight overhead, but the impact is likely negligible for small to moderately-sized dictionaries. Great job.

**Comment by Only1allan** [comment]
Do you have a better way to remove the negligible error? Or since it's negligible we just stick with it?

Also let me fix the merge conflict. Sorry about that.

**Comment by kariukikinyanjui** [comment]
It's negligible so let's stick with it.

**Review by kariukikinyanjui — COMMENTED** [review]
It's still a mystery how small changes make all the difference.

**Pull request merged**
